### ISSUE TITLE
About download datasets

### ISSUE THREAD

**Issue by 504115681** [dzunigan/uma_vi_tools#2]
Hello, thank you for sharing your excellent dataset, now I have some problems, the dataset cannot be downloaded through https://mapir.isa.uma.es/mapirwebsite/?p=2108&page=2 , please check the download link, thanks!

**Comment by DrZ-21** [comment]
hi,did you succeed?i couldn't download it either.

**Comment by AlbertoJaenal** [comment]
Hi, guys!!
Sorry about the late response. We did not notice that the server was down until some of you contacted us directly.
As a temporal solution, we uploaded the data in this [link](https://uma365-my.sharepoint.com/personal/alberto_jaenal_uma_es/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Falberto%5Fjaenal%5Fuma%5Fes%2FDocuments%2FUMA%5FVI&ga=1).
Please, contact us by e-mail if you have any issue.
Bye!
